layout_spectrum: 0.8046595
typography_spectrum: 0.4103943
color:
  saturation: 0.749104
  lightness: 0.7795699
  brandStrength: 0.1297099
  brandColors:
    - '#FFFFFF'
    - '#D3C996'
    - '#4D4D4D'
    - '#777777'
    - '#2E2E2E'
  rhythmicContrast: 0.7392672
name: Testgold
